### PR TITLE
 #161045486 create index page

### PR DESCRIPTION
**Pull request by kikimay**
**What does this PR do?**

It creates the landing page for the app.

**Description of Task to be completed?**
The task at hand was to create a user interface that is the landing page. This is the first page that users interact with.
**How should this be manually tested?**
Create a folder in your machine.
cd into that folder and clone my repo into that folder using the following git command: git clone https://github.com/kikimay/Store-manager-.git
open the folder in which you cloned the repo. open store manager folder and launch the index
file using your favorite web browser.

**Any background context you want to provide?**
This is just the landing page.

**What are the relevant pivotal tracker stories?**
161045486
**screenshots**
index la

### CODE REVIEW

**Comment by cod3smith** [comment]
Hey, I would like to suggest that you change the background color. Then when it comes to formatting your PR, make your titles bold and either include the link to your PT story or make the Story Id a link that way it is easier for the reviewer to access your PT story.

**Comment by unah254** [comment]
Check your PR naming, use[ this](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices). Bold the titles. I feel you could make the page look better than this.

**Comment by Makavura** [comment]
Bold UI. perhaps you could place the (c) 2018 at the bottom. Also, use this https://www.canva.com/color-palette/ to generate colour ranges that you can use to achieve a more balanced look in your UI. 
thanks

**Comment by kikimay** [comment]
> Hey, I would like to suggest that you change the background color. Then when it comes to formatting your PR, make your titles bold and either include the link to your PT story or make the Story Id a link that way it is easier for the reviewer to access your PT story.

**Comment by kikimay** [comment]
> Hey, I would like to suggest that you change the background color. Then when it comes to formatting your PR, make your titles bold and either include the link to your PT story or make the Story Id a link that way it is easier for the reviewer to access your PT story.

thanks. implementing feedback

**Comment by kikimay** [comment]
> Check your PR naming, use[ this](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices). Bold the titles. I feel you could make the page look better than this.

cool.thanks

**Pull request merged**
